### ISSUE TITLE
Git clone just got 2 empty notebooks

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [keitakurita/torchtext_tutorials#1]
Looking forward to this - but I just ended up with 2 files called Lesson 1 and Lesson 2 - no file extensions and 0 bytes long. I've manually downloaded the notebooks but you might want to check everything is working OK :) This may be to do with the colon embedded in the Notebook name, I am on Windows...

**Comment by keitakurita** [comment]
Thanks for the notice! This doesn't seem to happen on my mac or in a Linux environment, so it might be a Windows issue...I've seen several users run the notebooks on Windows though, and haven't heard anyone report this issue, but if it is a recurring issue I'll change the filenames.

**Comment by ChrisPalmerNZ** [comment]
I've figured it out - when a notebook has a colon in the title windows stops at the point it encounters the colon and you end up with a 0 byte file - these notebooks both have colons in the titles immediately after the Lesson 1 and Lesson 2 portions of their titles.

**Comment by keitakurita** [comment]
Changed the filenames
