### ISSUE TITLE
Windows issue Notebook 1

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [keitakurita/torchtext_tutorials#2]
There are problems in both notebooks with getting unexpected handling of text under Windows.

Notebook 1 fails when processing text because it encounters embedded \r\n characters and stops further loading of the particular line. For instance the first line reads "Explanation\r\nWhy the edits made under my use.." and Windows cannot load any more after the \r\n. 

These are the results of interrogating trn[0]:

trn[0].__dict__.keys()
dict_keys(['comment_text'])

trn[0].comment_text[:3]
['explanation']

Consequently the Iterator fails because of the unexpected structure.

A workaround is to strip out the offending characters with a routine and loading the fixed files (see below), but it may be viable to add handling of this to the tokenizer.

def fix_csv():
    df_train = pd.read_csv("data/train.csv")
    df_train["comment_text"] = df_train.comment_text.str.replace("\r\n", " ")
    df_train.to_csv("datafixed/train.csv", index=False, encoding = "utf-8")

    df_valid = pd.read_csv("data/valid.csv")
    df_valid["comment_text"] = df_valid.comment_text.str.replace("\r\n", " ")
    df_valid.to_csv("datafixed/valid.csv", index=False, encoding = "utf-8")

    df_test = pd.read_csv("data/test.csv")
    df_test["comment_text"] = df_test.comment_text.str.replace("\r\n", " ")
    df_test.to_csv("datafixed/test.csv", index=False, encoding = "utf-8")

**Comment by keitakurita** [comment]
Hi Zohaggie. What version of torchtext are you using?
As I've mentioned in the update README.md, you should install torchtext from the master branch of torchtext, not the pip repository. 
You can install using the command 
`pip install --upgrade git+https://github.com/pytorch/text`
I suspect that this should fix the newline handling problem.

**Comment by ChrisPalmerNZ** [comment]
Yes, thanks that did fix the issue. I was reluctant to upgrade as I didn't know if the most recent version might not be compatible with my fast.ai system running under windows, but its more windows compatibility will likely help - I'll know soon enough :)
