### ISSUE TITLE
Windows issue Notebook 2

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [keitakurita/torchtext_tutorials#3]
This is a decoding issue, and I cannot figure out how to fix it :(

WikiText2.splits(TEXT) fails when trying to use the standard Windows IncrementalDecoder in cp1252.py. I suppose it's the classic situation of a presumption of a UTF-8 environment, which is not the native one for Windows:

D:\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 40: character maps to <undefined>

The usual workaround I have used for these sorts of issues is to open a file with encoding="UTF-8", as I have for another issue described here. However I do not see any way to specify encoding to the WikiText2.splits method, so it might be better if we have instruction on how to set up the data manually after extracting the data files from the zip file.

I have explored the idea of using locale.setlocale to specify encoding, but I cannot figure out how to use it. For example:

import locale
locale.getpreferredencoding()
'cp1252'

locale.setlocale(locale.LC_ALL, 'utf-8')
Error: unsupported locale setting

vs:
locale.setlocale(locale.LC_ALL, 'en-AU')
'en-AU'

vs:
locale.setlocale(locale.LC_ALL, ('en-AU', 'utf-8'))  # tried variations of case and use of underscore as well
Error: unsupported locale setting

**Comment by keitakurita** [comment]
Hi Zohaggie. I think this issue has also been addressed in the master branch of torchtext (please refer to my comment on #2 
If the problem persists, it seems more like an issue to file to torchtext, so raise an issue there (I'm a contributor to torchtext so I'll be happy to address your bug there if you can file a more detailed issue)

**Comment by ChrisPalmerNZ** [comment]
Yes, issue has been fixed after upgrading as instructed on #2 - thanks!
