### ISSUE TITLE
Last timestep output in the text classifier wrong?

### ISSUE THREAD

**Issue by surajnair04** [keitakurita/torchtext_tutorials#5]
The `hdn[-1,:,:]` doesn't seem to return the last timestep output for variable length sequences.
E.g. If there are two sentences in my batch, one of length 20 and another of length 10, then -1 would slice the correct output for first sentence but not for second sentence

``` python
    def forward(self, seq):
        hdn, _ = self.encoder(self.embedding(seq))
        feature = hdn[-1, :, :]
        for layer in self.linear_layers:
            feature = layer(feature)
        preds = self.predictor(feature)
        return preds
```

Shouldn't it be something similar to this 
[https://stackoverflow.com/questions/46387661/how-to-correctly-implement-a-batch-input-lstm-network-in-pytorch](url)

**Comment by keitakurita** [comment]
Torchtext pads input sequences prior to input, so variable length sequences aren't something we need to worry about.
